name: Feature Request
description: Suggest an idea for memory.journal
title: "enh: "
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to memory.journal
        - label: >
            Changing existing functionality in memory.journal
        - label: >
            Removing existing functionality in memory.journal

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve.
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using pseudocode if relevant.
    validations:
      required: true
