DROP TABLE IF EXISTS journal;
DROP TABLE IF EXISTS memory;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS memory_tag;

CREATE TABLE journal (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	journalname TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT UNIQUE NOT NULL
);

CREATE TABLE memory (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	journal_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	memorydate TIMESTAMP NOT NULL, 
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	FOREIGN KEY (journal_id) REFERENCES journal (id)
);

CREATE TABLE memory_tag (
	journal_id INTEGER NOT NULL,
	memory_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	FOREIGN KEY (journal_id) REFERENCES journal (id),
	FOREIGN KEY (memory_id) REFERENCES memory (id),
	FOREIGN KEY (tag_id) REFERENCES tag (id)
	PRIMARY KEY (journal_id, memory_id, tag_id)
);
